site_name: ParKit Documentation

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - navigation.expand

nav:
    - Home: index.md
    - Objects and Namespaces: object.md
    - Advanced Usage: advanced.md
    - Using Collections: collections.md
    - Using Process: process.md
    - API Reference: api.md

markdown_extensions:
  - meta
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
