import multiprocessing

from parkit.typeddicts import Profiles

PROCESS_UUID_ENVNAME: str = 'PARKIT_PROCESS_UUID'

PID_FILENAME_PREFIX: str = 'parkit-'
PID_FILENAME_EXTENSION: str = '.pid'

CLUSTER_SITE_UUID_ENVNAME: str = 'PARKIT_CLUSTER_SITE_UUID'
CLUSTER_STORAGE_PATH_ENVNAME: str = 'PARKIT_CLUSTER_STORAGE_PATH'
NODE_UID_ENVNAME: str = 'PARKIT_NODE_UID'
CLUSTER_UID_ENVNAME: str = 'PARKIT_CLUSTER_UID'

DEFAULT_PROCESS_TERMINATION_TIMEOUT: float = 1.
DEFAULT_CLUSTER_CONCURRENCY: int = min(max(4, multiprocessing.cpu_count()), 8)
DEFAULT_MONITOR_POLLING_INTERVAL: float = 5.
DEFAULT_WORKER_POLLING_INTERVAL: float = 0.05
DEFAULT_ADAPTER_POLLING_INTERVAL: float = 0.05
DEFAULT_SCHEDULER_HEARTBEAT_INTERVAL: float = 1.

PROCESS_TERMINATION_TIMEOUT_ENVNAME: str = 'PARKIT_PROCESS_TERMINATION_TIMEOUT'
CLUSTER_CONCURRENCY_ENVNAME: str = 'PARKIT_CLUSTER_CONCURRENCY'
MONITOR_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_MONITOR_POLLING_INTERVAL'
WORKER_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_WORKER_POLLING_INTERVAL'
ADAPTER_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_ADAPTER_POLLING_INTERVAL'
SCHEDULER_HEARTBEAT_INTERVAL_ENVNAME: str = 'PARKIT_SCHEDULER_HEARTBEAT_INTERVAL'

SELF_ENVNAME: str = 'PARKIT_SELF_REFERENCE'

ANONYMOUS_SCOPE_FLAG_ENVNAME: str = 'PARKIT_GC_SCOPE'

PARKIT_TEMP_SITE_DIRNAME: str = 'parkit'
GLOBAL_SITE_STORAGE_PATH_ENVNAME: str = 'PARKIT_GLOBAL_SITE_STORAGE_PATH'
GLOBAL_FILE_LOCK_PATH_ENVNAME: str =  'PARKIT_GLOBAL_FILE_LOCK_PATH'
GLOBAL_FILE_LOCK_FILENAME: str = 'parkit.global.lock'

DEFAULT_SITE_PATH: str = 'DEFAULT_SITE_PATH'
DEFAULT_SITE_NAME: str = 'DEFAULT_SITE_NAME'

LMDB_WRITE_MAP_ENVNAME: str = 'LMDB_WRITE_MAP'
LMDB_MAP_ASYNC_ENVNAME: str = 'LMDB_MAP_ASYNC'
LMDB_METASYNC_ENVNAME: str = 'LMDB_METASYNC'
LMDB_MAX_DBS_ENVNAME: str = 'LMDB_MAX_DBS'
LMDB_READONLY_ENVNAME: str = 'LMDB_READONLY'
LMDB_SYNC_ENVNAME: str = 'LMDB_SYNC'
LMDB_READAHEAD_ENVNAME: str = 'LMDB_READAHEAD'
LMDB_MEMINIT_ENVNAME: str = 'LMDB_MEMINIT'
LMDB_MAX_SPARE_TXNS_ENVNAME: str = 'LMDB_MAX_SPARE_TXNS'
LMDB_MAX_READERS_ENVNAME: str = 'LMDB_MAX_READERS'
LMDB_PROFILE_ENVNAME: str = 'LMDB_PROFILE'
LMDB_INITIAL_MAP_SIZE_ENVNAME: str = 'LMDB_INITIAL_MAP_SIZE'

LMDB_PROFILES: Profiles = dict(
	default = {
		'LMDB_INITIAL_MAP_SIZE': 134217728,
		'LMDB_WRITE_MAP': True,
		'LMDB_METASYNC': True,
		'LMDB_MAP_ASYNC': True,
		'LMDB_MAX_DBS': 65536,
		'LMDB_READONLY': False,
		'LMDB_SYNC': True,
		'LMDB_READAHEAD': False,
		'LMDB_MEMINIT': False,
		'LMDB_MAX_SPARE_TXNS': multiprocessing.cpu_count(),
		'LMDB_MAX_READERS': 256
	},
	memory = {
		'LMDB_INITIAL_MAP_SIZE': 134217728,
		'LMDB_WRITE_MAP': False,
		'LMDB_METASYNC': False,
		'LMDB_MAP_ASYNC': False,
		'LMDB_MAX_DBS': 65536,
		'LMDB_READONLY': False,
		'LMDB_SYNC': False,
		'LMDB_READAHEAD': False,
		'LMDB_MEMINIT': False,
		'LMDB_MAX_SPARE_TXNS': multiprocessing.cpu_count(),
		'LMDB_MAX_READERS': 256
	}
)

ENVIRONMENT_UUID_KEY: str = '__uuid__'

ROOT_NAMESPACE: str = ''
DEFAULT_NAMESPACE: str = 'default'
MEMORY_NAMESPACE: str = 'memory'
SCHEDULER_NAMESPACE: str = '__sched__'
SYNCHRONIZED_NAMESPACE: str = 'memory'
EXECUTION_NAMESPACE: str = '__exec__'
MODULE_NAMESPACE: str = 'module'

GLOBAL_SITE_NAME: str = '__global__'
SCOPE_TABLE_NAME: str = '__scope_table__'

EXECUTION_QUEUE_PATH: str = '__exec__/__execution_queue__'
NODE_TERMINATION_QUEUE_PATH: str = '__exec__/__node_termination_queue__'
CLUSTER_STATE_DICT_PATH: str = '__exec__/__cluster_state_dict__'
EXECUTION_INDEX_PATH: str = '__exec__/__execution_index__'
SYSLOG_PATH: str = 'memory/__syslog__'
PID_TABLE_DICT_PATH: str = 'memory/__pid_table__'

ATTRIBUTE_DATABASE: str = '__attribute__'
VERSION_DATABASE: str = '__version__'
NAME_DATABASE: str = '__name__'
DESCRIPTOR_DATABASE: str = '__descriptor__'
