# pylint: disable = not-callable
import multiprocessing

from parkit.typeddicts import Profiles

PID_FILENAME_PREFIX: str = 'parkit-'
PID_FILENAME_EXTENSION: str = '.pid'

DEFAULT_PYTHON_NAMES: str = 'python.exe,pythonw.exe,python'
PYTHON_NAMES_ENVNAME: str = 'PARKIT_PYTHON_NAMES'

NODE_UID_ENVNAME: str = 'PARKIT_NODE_UID'
CLUSTER_UID_ENVNAME: str = 'PARKIT_CLUSTER_UID'

DEFAULT_PROCESS_TERMINATION_TIMEOUT: float = 1.
DEFAULT_POOL_AUTOSTART: bool = True
DEFAULT_POOL_SIZE: int = max(4, multiprocessing.cpu_count())
DEFAULT_MONITOR_POLLING_INTERVAL: float = 5
DEFAULT_WORKER_POLLING_INTERVAL: float = 0.1
DEFAULT_ADAPTER_POLLING_INTERVAL: float = 0.05
DEFAULT_GARBAGE_COLLECTOR_POLLING_INTERVAL: float = 300
DEFAULT_MONITOR_RESTARTER_POLLING_INTERVAL: float = 60

PROCESS_TERMINATION_TIMEOUT_ENVNAME: str = 'PARKIT_PROCESS_TERMINATION_TIMEOUT'
POOL_AUTOSTART_ENVNAME: str = 'PARKIT_POOL_AUTOSTART'
POOL_SIZE_ENVNAME: str = 'PARKIT_POOL_SIZE'
MONITOR_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_MONITOR_POLLING_INTERVAL'
WORKER_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_WORKER_POLLING_INTERVAL'
ADAPTER_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_ADAPTER_POLLING_INTERVAL'
GARBAGE_COLLECTOR_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_GARBAGE_COLLECTOR_POLLING_INTERVAL'
MONITOR_RESTARTER_POLLING_INTERVAL_ENVNAME: str = 'PARKIT_MONITOR_RESTARTER_POLLING_INTERVAL'

SELF_ENVNAME: str = 'PARKIT_SELF_REFERENCE'

PARKIT_TEMP_INSTALLATION_DIRNAME: str = 'parkit'

PROCESS_UUID_ENVNAME: str = 'PARKIT_PROCESS_UUID'

STORAGE_PATH_ENVNAME: str = 'PARKIT_STORAGE_PATH'

LMDB_WRITE_MAP_ENVNAME: str = 'LMDB_WRITE_MAP'
LMDB_MAP_ASYNC_ENVNAME: str = 'LMDB_MAP_ASYNC'
LMDB_METASYNC_ENVNAME: str = 'LMDB_METASYNC'
LMDB_MAX_DBS_ENVNAME: str = 'LMDB_MAX_DBS'
LMDB_READONLY_ENVNAME: str = 'LMDB_READONLY'
LMDB_SYNC_ENVNAME: str = 'LMDB_SYNC'
LMDB_READAHEAD_ENVNAME: str = 'LMDB_READAHEAD'
LMDB_MEMINIT_ENVNAME: str = 'LMDB_MEMINIT'
LMDB_MAX_SPARE_TXNS_ENVNAME: str = 'LMDB_MAX_SPARE_TXNS'
LMDB_MAX_READERS_ENVNAME: str = 'LMDB_MAX_READERS'
LMDB_PROFILE_ENVNAME: str = 'LMDB_PROFILE'
LMDB_INITIAL_MAP_SIZE_ENVNAME: str = 'LMDB_INITIAL_MAP_SIZE'

LMDB_PROFILES = Profiles(
	default = {
		'LMDB_INITIAL_MAP_SIZE': 1073741824,
		'LMDB_WRITE_MAP': True,
		'LMDB_METASYNC': True,
		'LMDB_MAP_ASYNC': True,
		'LMDB_MAX_DBS': 65536,
		'LMDB_READONLY': False,
		'LMDB_SYNC': True,
		'LMDB_READAHEAD': False,
		'LMDB_MEMINIT': False,
		'LMDB_MAX_SPARE_TXNS': multiprocessing.cpu_count(),
		'LMDB_MAX_READERS': 64
	}
)

SETTINGS_NAMESPACE: str = '__settings__'
DEFAULT_NAMESPACE: str = 'default'
TASK_NAMESPACE: str = 'task'
SYSLOG_NAMESPACE: str = '__syslog__'

TASK_QUEUE_PATH: str = 'task/__task_queue__'
NODE_TERMINATION_QUEUE_PATH: str = 'task/__node_termination_queue__'
POOL_STATE_DICT_PATH: str = 'task/__pool_state_dict__'
SYSLOG_PATH: str = '__syslog__/syslog'

SETTINGS_DATABASE: str = '__settings__'
ATTRIBUTE_DATABASE: str = '__attribute__'
VERSION_DATABASE: str = '__version__'
NAME_DATABASE: str = '__name__'
DESCRIPTOR_DATABASE: str = '__descriptor__'
